version: 0.2

env:
  # Reference the secret stored in AWS Secrets Manager
  # These provide the DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD variables
  secrets-manager:
    DOCKERHUB_USERNAME: DockerHubCredentialsForGenDJ:DOCKERHUB_USERNAME # SecretName:JSONKey
    DOCKERHUB_PASSWORD: DockerHubCredentialsForGenDJ:DOCKERHUB_PASSWORD # SecretName:JSONKey
  # IMAGE_REPO_NAME and IMAGE_TAG are expected to be set as environment
  # variables directly on the CodeBuild project by the setup_codebuild.py script.

phases: # Top level key
  install: # Level 1 dictionary key under phases
    commands: # Level 2 list key under install
      - echo "--- Install Phase Minimal ---"
      # We'll add the actual install commands back later if this works
      - pip --version || pip3 --version || echo "Pip not found"
  pre_build: # Level 1 dictionary key under phases
    commands: # Level 2 list key under pre_build
      - echo "--- Pre-Build Phase Minimal ---"
      # Minimal command to test phase transition
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  build: # Level 1 dictionary key under phases
    commands: # Level 2 list key under build
      - echo "--- Build Phase Minimal ---"
      # Minimal command
      - echo "Build phase placeholder"
  post_build: # Level 1 dictionary key under phases
    commands: # Level 2 list key under post_build
      - echo "--- Post-Build Phase Minimal ---"
      # Minimal command
      - echo "Post-build phase placeholder"

# artifacts: # Top level key (Ensure this line starts at column 0 or same level as 'phases' and 'env')
#   files:   # Level 1 dictionary key under artifacts
#     - '**/*' # Level 2 list item
